### ISSUE TITLE
Account Type Administrator doesnt work

### ISSUE THREAD

**Issue by salihzett** [ninxsoft/MacUserGenerator#1]
I choose "Administrator" but after I have installed the pkg, i take "Standard".
What is wrong?! :/

**Comment by ilovefood2** [comment]
I have same issue, created with admin account pkg and after install, account is standard
im in 10.13.3

**Comment by Tafkaroll** [comment]
Same issue here. Only the standard account type can be created.

**Comment by blackberryhell** [comment]
Same here, I created a script and noticed it doesn't add the user to the admin group in the script, add this line to the script and it will make the user admin.

dseditgroup -o edit -a "$userName" -t user admin

**Comment by ninxsoft** [comment]
Have fixed Administrator account type selection via `PlistBuddy` instead of `dseditgroup` or `defaults write`

Apologies for the delay, and thanks for the nudge!

**Comment by blackberryhell** [comment]
No worries, keep up the good work!
