### ISSUE TITLE
Doesn't create a dscl entry for a new user in Mojave

### ISSUE THREAD

**Issue by roadrunnersrg** [ninxsoft/MacUserGenerator#11]
After testing here, another issue with this software is that (at least in Mojave 10.14.2) the app does not appear to be generating a "dscl" user, only a home folder.  The mac GUI does both when you create a new user in System Preferences-Users&Groups.

**Comment by ninxsoft** [comment]
Support for Mojave is underway, will have some good news soon.

Duplicate of #7
