### ISSUE TITLE
Full home drive folder population

### ISSUE THREAD

**Issue by roadrunnersrg** [ninxsoft/MacUserGenerator#3]
Is it expected for MacUserGenerator 0.2 under macOS 10.13.4 (Build 17E202) to not fully populate the home folder of a newly created user?

For a MacUserGenerated user it get these directories (with version 0.2):

Testuser

computer1:~ testuser$ ls -l /Users/testuser/
total 0
drwx------   2 testuser  admin    68 May 30 08:45 Desktop
drwxr-xr-x   2 testuser  admin    68 May 30 08:45 Documents
drwx------   2 testuser  admin    68 May 30 08:45 Downloads
drwx------@ 31 testuser  admin  1054 May 30 08:46 Library
drwxr-xr-x   3 testuser  admin   102 May 30 08:45 isus
PRE102A2:~ testuser$ 

And for locally generated user (from the Accounts pane) I get these directories:

computer1:~ testuser$ ls -l /Users/testuser-local
total 0
drwx------+  3 testuser-local  staff  102 May 30 08:53 Desktop
drwx------+  3 testuser-local  staff  102 May 30 08:53 Documents
drwx------+  3 testuser-local  staff  102 May 30 08:53 Downloads
drwx------+ 27 testuser-local  staff  918 May 30 08:53 Library
drwx------+  3 testuser-local  staff  102 May 30 08:53 Movies
drwx------+  3 testuser-local  staff  102 May 30 08:53 Music
drwx------+  3 testuser-local  staff  102 May 30 08:53 Pictures
drwxr-xr-x+  4 testuser-local  staff  136 May 30 08:53 Public

**Comment by ninxsoft** [comment]
To my knowledge I am not populating the user's home directory, I am leaving the OS to take care of this upon first login.

I will look into this 🤔

**Comment by DomG62462** [comment]
Also MacUserGenerator 0.2 under macOS 10.13.4 and finding that the user only gets /Library/Preferences/ folder with nothing in it.
When logging in all the user assistant pages are showing up.
Not sure if it matters, but I set the home folder to /var/

**Comment by roadrunnersrg** [comment]
The assistant page defeat (SetupAssistant) features worked for me in my tests here.  I chose to defeat every popup the GUI made available.

**Comment by roadrunnersrg** [comment]
Retested with 10.13.5 update today.  The home folder items of ~/Music can be dynamically created on demand by the OS by a launch of iTunes, but ~/Pictures and ~/Movies cannot.  This produces errors such as 'An Unexpected Error Has Occurred' from apps like Apple Photos 3.0 and Apple iMovie 10.1.9.  Accounts created in the macOS GUI populate these directories as soon as an account is created.

**Comment by ToddToddTodd** [comment]
I'm having the same issue. I only see the Desktop, Documents, Downloads, & Library folder.

**Comment by ninxsoft** [comment]
This is now fixed: 432037c

- Home folders are now fully created when run on booted volumes
- `~/Library/Preferences/` is created when run on targeted volumes
  - All remaining folders should populate dynamically upon first login

Tested on macOS High Sierra **10.13.6** and macOS Mojave **10.14.5**
