### ISSUE TITLE
Account Name and Home Folder Capitalization

### ISSUE THREAD

**Issue by dustinjlandgraf** [ninxsoft/MacUserGenerator#4]
When the Full Name has capital letters and spaces, the first capital letter is properly changed to lower case, but others are not. 
Example: Full name "Tech Admin" has the account name populated as "techAdmin", and the home folder set to "/Users/techAdmin".

**Comment by ninxsoft** [comment]
This is now fixed - spaces are stripped and uppercase letters are converted to lowercase.
