### ISSUE TITLE
Mojave compatibility

### ISSUE THREAD

**Issue by jmahlman** [ninxsoft/MacUserGenerator#7]
Not sure if you're testing this against any betas currently but creating an account in the current Mojave beta (beta 8) does not work. 

No account created at all using PKG. Script was not tested.

**Comment by fulltimecasual** [comment]
Yep, not working here.

**Comment by jmahlman** [comment]
Looks like @gregneagle is working on an update for 10.14. https://github.com/gregneagle/pycreateuserpkg/tree/od_api

**Comment by mbezzo** [comment]
Same.  Would love to see this working on Mojave.  Anybody have any idea why it isn't?  I get the Users/username folder created, but as far as I can tell that's the only thing that happens. Same for .pkg or script.

**Comment by mistacabbage** [comment]
I am trying to run Mojave's startosinstall from Terminal in the Recovery volume and I get this error.

Error: The specified file is not a valid product archive (path/to/pkghere.pkg).
Please see the usage guide for more information.

**Comment by ninxsoft** [comment]
Latest build works with macOS Mojave **10.14.5**:

- Tested on booted volume
- Tested on targeted volume
- Tested with System Integrity enabled
- Tested with System Integrity disabled
