### ISSUE TITLE
Generate a new UUID

### ISSUE THREAD

**Issue by zone11** [ninxsoft/MacUserGenerator#8]
Once a new document is generated, the UUID of a user generate from this document stays the same.
Even if I change the username in the document to work with like a template, it stays the same.

Possible Solutions:
- Generate new UUID with every field change
- Button to generate new UUID
- Add UUID generation to the exported product

Cheers,
Christian

**Comment by ninxsoft** [comment]
A new UUID is generated everytime the exported package / script is run.

This has been fixed in https://github.com/ninxsoft/MacUserGenerator/commit/6d363e0565981352bc3cd2ec87a00a080f4791bc
