### ISSUE TITLE
Check user or ID not already used

### ISSUE THREAD

**Issue by gsmc-alx** [ninxsoft/MacUserGenerator#9]
How about adding an option to check if the user already exists, or the ID is already in use?

I exported the user-creation script, and added the following, before setUser() is called:

```
##############################
# EXTRA CHECKS ADDED BY ALX ##
##############################

# Check if user .plist already exists (assume user exists, if so)
if [ -e "$target/private/var/db/dslocal/nodes/Default/users/$name.plist" ]
then
	# User exists, exit early
	echo "ERROR: User $name exists, unable to continue"
	exit 1
fi

# Check ID not already in use
for file in $(find "$target/private/var/db/dslocal/nodes/Default/users" -type f )
do
	if [ "`/usr/libexec/PlistBuddy -c "Print :uid:0" $file`" == "$uid" ]
	then
		# User ID already used, exit early
		echo "ERROR: ID $uid already used, unable to continue"
		exit 1
	fi
done
```
I'm no Bash expert, so I'm sure this could be done better.

I also realise that there are better way to check if a user exists, or an ID has been used, assuming the   package is being installed locally. I wanted to make sure the checks would work even if the package was being installed on another drive (say while booted to the Recovery partition).

I don't know how robust these checks are. As I said, I'm no Bash expert, so I'm sure this feature could be implemented better.

**Comment by ninxsoft** [comment]
This is now fixed: https://github.com/ninxsoft/MacUserGenerator/commit/92adfd93323052a0a07768e3533075da40788155

- Will check for user account (shortname), abort if one is found (both booted volumes and targeted volumes)
- Will check for user id (uid), abort if one is found (both booted volumes and targeted volumes)
